// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbUiSQbbmc6ayRvDrsuLLYg3Yu2mu5JKA',
    appId: '1:148742636444:web:b2c50250b777d7775bfe59',
    messagingSenderId: '148742636444',
    projectId: 'kiswani2',
    authDomain: 'kiswani2.firebaseapp.com',
    databaseURL: 'https://kiswani2-default-rtdb.firebaseio.com',
    storageBucket: 'kiswani2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fB0FqFr-ootpDK6W71SlFRdw5bkZKTc',
    appId: '1:148742636444:android:d8346560260da0b65bfe59',
    messagingSenderId: '148742636444',
    projectId: 'kiswani2',
    databaseURL: 'https://kiswani2-default-rtdb.firebaseio.com',
    storageBucket: 'kiswani2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDDrGpW0TnucWAlGi515YQeZH-N5aHPE',
    appId: '1:148742636444:ios:9f7e1f338ad30cdc5bfe59',
    messagingSenderId: '148742636444',
    projectId: 'kiswani2',
    databaseURL: 'https://kiswani2-default-rtdb.firebaseio.com',
    storageBucket: 'kiswani2.appspot.com',
    iosBundleId: 'com.example.finalProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJDDrGpW0TnucWAlGi515YQeZH-N5aHPE',
    appId: '1:148742636444:ios:79ad2319975208715bfe59',
    messagingSenderId: '148742636444',
    projectId: 'kiswani2',
    databaseURL: 'https://kiswani2-default-rtdb.firebaseio.com',
    storageBucket: 'kiswani2.appspot.com',
    iosBundleId: 'com.example.finalProject1.RunnerTests',
  );
}
